__BASE__: "{fileDirname}/place_v0_joint_SCR.yaml"
BASE_TASK_CONFIG_PATH: "configs/rearrange/tasks/place_v1.yaml"

RL:
  ACTION_NAME: "BaseArmGripperAction2"

TOTAL_NUM_STEPS: 2e8
NUM_CHECKPOINTS: 200

GOAL:
  INIT_GRASPED: True
  TRAINER_NAME: "skill-goal-bilinear-ppo-v0"
  POLICY:
    name: BilinearCRPolicy
    BilinearCRNet:
      rgb_uuids: []
      depth_uuids:
        - "robot_head_depth"
        - "robot_arm_depth"
      goal_dep_state_uuids:
        - "place_goal_at_gripper"
        - "place_goal_at_base"
      goal_ind_state_uuids:
        - "arm_joint_pos"
        - "is_grasped"
        - "gripper_pos_at_base"
        - "object_orientation"
      hidden_size: 256
      state_hidden_sizes: []
      rnn_hidden_size: 256
    GAUSSIAN_ACTOR:
      std_init_bias: -1.0
      pre_bilinear_size: 256
    CRITIC:
      pre_bilinear_size: 256
    BASE_CHECKPOINT_PATH: "data/results/rearrange/skills/tidy_house_bilinear/place_v1_joint_SCR/alt_checkpoints_3/ckpt.116.pth"
    CHECKPOINT_FOLDER: "data/results/rearrange/skills/tidy_house_bilinear/place_v1_joint_SCR/goal_checkpoints_noise/"
    TENSORBOARD_DIR: "data/results/rearrange/skills/tidy_house_bilinear/place_v1_joint_SCR/goal_tb_noise/"
