__BASE__: "{fileDirname}/base.yaml"
BASE_TASK_CONFIG_PATH: "configs/rearrange/tasks/place_v0.yaml"

SENSORS:
  - "HEAD_DEPTH_SENSOR"
  - "ARM_DEPTH_SENSOR"

TOTAL_NUM_STEPS: 2e8
NUM_CHECKPOINTS: 200

RL:
  PPO:
    num_steps: 256
    gamma: 0.999

  ACTION_NAME: "ArmGripperAction2"
  REWARD_MEASURES:
    - "rearrange_place_reward"
    - "force_penalty"
    - "invalid_grasp_penalty"
  SUCCESS_MEASURE: rearrange_place_success
  SUCCESS_REWARD: 10.0
  SLACK_REWARD: -0.002

  POLICY:
    name: BilinearCRPolicy
    BilinearCRNet:
      rgb_uuids: []
      depth_uuids:
        - "robot_head_depth"
        - "robot_arm_depth"
      goal_dep_state_uuids:
        - "place_goal_at_gripper"
        - "place_goal_at_base"
      goal_ind_state_uuids:
        - "gripper_pos_at_base"
        - "arm_joint_pos"
        - "is_grasped"
        - "object_orientation"
      hidden_size: 256
      state_hidden_sizes: []
      rnn_hidden_size: 256
    GAUSSIAN_ACTOR:
      std_init_bias: -1.0
      pre_bilinear_size: 256
    CRITIC:
      pre_bilinear_size: 256
