__BASE__: "{fileDirname}/base.yaml"

ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

TASK:
  TYPE: RearrangePlaceTask-v0
  BASE_NOISE: 0.1
  BASE_ANGLE_NOISE: 0.25
  # OVERRIDE_BASE_NOISE: 0.7
  # OVERRIDE_BASE_ANGLE_NOISE: 0.75

  FRIDGE_INIT_RANGE: [1.5, 2.35]
  DRAWER_INIT_RANGE: [0.4, 0.5]
  USE_CACHE: False

  POSSIBLE_ACTIONS:
    - ArmGripperAction
    - ArmGripperAction2
  ACTIONS:
    ArmGripperAction:
      GRIPPER_ACTION:
        DISABLE_GRASP: True
    ArmGripperAction2:
      GRIPPER_ACTION:
        DISABLE_GRASP: True

  SENSORS:
    - ArmJointPositionSensor
    - GripperPositionSensor
    - IsGraspedSensor
    - PlaceGoalSensor
    - PlaceGoalSensor2
    - ObjectOrientationSensor

  MEASUREMENTS:
    - ObjectToGoalDistance
    - GripperToRestingDistance
    - GripperStatus
    - RobotForce
    - ForcePenalty
    - InvalidGraspPenalty
    - PlaceObjectSuccess
    - RearrangePlaceReward
    - RearrangePlaceSuccess
  ObjectToGoalDistance:
    TYPE: ObjectToGoalDistance
  GripperToRestingDistance:
    TYPE: GripperToRestingDistance
  GripperStatus:
    TYPE: GripperStatus
  RobotForce:
    TYPE: RobotForce
    MIN_DELTA_FORCE: 20.0
    INCLUDE_OBJ_COLLISIONS: True
  ForcePenalty:
    TYPE: ForcePenalty
    FORCE_PENALTY: 0.001
    MAX_FORCE_PENALTY: 0.2
    MAX_ACCUM_FORCE: -1.0
    MAX_ACCUM_FORCE_PENALTY: 1.0
  InvalidGrasp:
    TYPE: InvalidGrasp
  InvalidGraspPenalty:
    TYPE: InvalidGraspPenalty
    PENALTY: 1.0
    END_EPISODE: True
  PlaceObjectSuccess:
    TYPE: PlaceObjectSuccess
    THRESHOLD: 0.15
  RearrangePlaceSuccess:
    TYPE: RearrangePlaceSuccess
    THRESHOLD: 0.05
    OBJ_ROT_THRESHOLD: 0.01
    RESET_OBJ_MOVEMENT_TIMER: 40
  RearrangePlaceReward:
    TYPE: RearrangePlaceRewardV1
    DIST_REWARD: 4.0
    STABILITY_REWARD: 1.0
    ROT_REWARD: 4.0
    USE_DIFF: True
    HOLDING_THRESHOLD: 0.08
    RELEASE_REWARD: 10.0
    RELEASE_PENALTY: 1.0
    ORIENTATION_START_THRESHOLD: 0.2
    CONTINUED_SUCCESS_REWARD: 0.05
    END_DROP: True
